### ISSUE TITLE
ipc可以跟webview内部通信吗?

### ISSUE THREAD

**Issue by soymikey** [SugarTurboS/Sugar-Electron#12]
ipc可以跟webview内部通信吗? 用preload挂ipc到webview 的window 对象上, window.ipc请求返回的数据发送到webview的父页面,而不是webview. 这个有什么绕过的方法吗?

**Comment by 954053260** [comment]
设置webview nodeintegration 支持node运行环境，可以实现，如下：官方文档https://www.electronjs.org/docs/api/webview-tag#event-ipc-message

`
// In embedder page.
const webview = document.querySelector('webview')
webview.addEventListener('ipc-message', (event) => {
  console.log(event.channel)
  // Prints "pong"
})
webview.send('ping')
Copy
// In guest page.
const { ipcRenderer } = require('electron')
ipcRenderer.on('ping', () => {
  ipcRenderer.sendToHost('pong')
})
`

**Comment by soymikey** [comment]
感谢大佬回复, 我现在就是用ipcRenderer 来通信的, 但是我在想 有没有办法把框架的ipc挂载到webview的全局对象上, 然后用webview的全局对象的ipc.request 来和 main线程的ipc.response来通信?

目前在把ipc挂载到webview和main 的ipc通信的时候, webview 上调用ipc.request 调试工具 显示:{code: 3, msg: "访问超时"}

**Comment by 954053260** [comment]
ipc模块目前不支持webview与主进程的通信。从实现方面可以兼容到，近期版本发布支持。
