### ISSUE TITLE
electron-builder打包的时候可以通过npm的script 来打不通的环境吗?

### ISSUE THREAD

**Issue by soymikey** [SugarTurboS/Sugar-Electron#14]
目前看文档知道可以在开发环境下 通过env=dev 或者env=test 来获取不同环境的配置, 我想请教的是 如果我们用electron builder打包的会默认使用config.js下的配置. 那我们有没有什么办法在打包的时候通过指定使用哪个配置吗?或者可以通过script 里面的参数来打包不同环境的配置呢?  谢谢

**Comment by 954053260** [comment]
目前是不支持的，通过一个配置使用哪个环境，是否能满足需求呢？比config.base.js 可以配置env=test 那么默认就是测试环境
