### ISSUE TITLE
sugar-electron-cli 已安装，路径也正确，依旧报错

### ISSUE THREAD

**Issue by z5252753** [SugarTurboS/Sugar-Electron#18]
'sugar-electron-cli' 不是内部或外部命令，也不是可运行的程序
或批处理文件。 
已经执行了 
npm i sugar-electron-cli -g

sugar-electron-cli init

**Comment by 954053260** [comment]
我这边试了，是可以使用的。

`npm i sugar-electron-cli -g`

安装成功后，命令行窗口有重启吗？

**Comment by 954053260** [comment]
已经恢复
